on:
  push:
    branches: [master]

name: Generate GH Pages

jobs:
  build:
    name: Build GH Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - run: rustup target install wasm32-unknown-unknown
      - run: cargo install -f wasm-bindgen-cli --version 0.2.84
      - run: cargo build --release --target wasm32-unknown-unknown
      - run: wasm-bindgen --out-dir wasm --target web target/wasm32-unknown-unknown/release/bevyroids.wasm

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./wasm
